name: Publish

on:
  push:
    branches:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    environment:
      name: TEST
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_PRODUCT_CODE: ${{ secrets.TEST_PRODUCT_CODE }}
          TEST_PLAN_CODE: ${{ secrets.TEST_PLAN_CODE }}
          TEST_ITEM_CODE: ${{ secrets.TEST_ITEM_CODE }}
          TEST_PROMO_CODE: ${{ secrets.TEST_PROMO_CODE }}
        run: npm test

      - name: Publish to JSR
        run: npx jsr publish --allow-dirty
